name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install MoonBit CLI
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"
      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 24
          cache: "pnpm"
      - name: Generate CommonMark tests
        run: node scripts/gen-tests.js
      - name: Generate GFM tests
        run:  node scripts/gen-gfm-tests.js
      - name: Check
        run: |
          moon update
          moon check
      - name: Test all
        run: |
          moon test src --target js,native,wasm-gc
      - name: Test CommonMark compatibility
        run: |
          moon test src/cmark_tests --target js
      - name: Test GFM compatibility
        run: |
          moon test src/gfm_tests --target js
      - name: Test HTML rendering
        run: |
          moon test src/html_tests --target js
      - name: Test TUI rendering
        run: |
          moon test src/tui --target all
      - name: Test Bench
        run: moon bench
      - name: Component build (wasm)
        run: |
          cd component
          moon build --target wasm --release
